version: "3"
services:
  frontend-container:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/frontend
      - /frontend/node_moduls
    environment:
      - NODE_ENV=development
    