version: "3"
services:
  backend-container:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/backend
      - /backend/node_moduls
    environment:
      - NODE_ENV=development
    command: npm run watch
    